# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 04:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_auto_20170227_0513'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=140)),
                ('Password', models.CharField(max_length=140)),
            ],
        ),
    ]
