# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0006_profilephotos'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilephotos',
            name='person',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
