# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0008_delete_profilephotos'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilePhotos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=b'')),
                ('person', models.CharField(max_length=500)),
            ],
        ),
    ]
