# Generated by Django 2.0 on 2017-03-19 12:25

from django.db import migrations, models
import photos.models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0010_delete_profilephotos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memes',
            name='photo_link',
            field=models.FileField(upload_to=photos.models.get_upload_file_name),
        ),
    ]
